sound editor: "mod matrix" overview over all active patch cables
SynthstromAudible/DelugeFirmware pull request #157
Opened 2023-07-05 22:12 UTC by bfredl

This provides a quick overview over all modulation which is active as part of a sound, similar to a "mod matrix" screen present in many synths.

TODO:
- [ ] fine tune the UI for OLED. When a cable only have one source, we could fill in the current strength value in the "src2" slot
- [ ] fine tune the UI for 7SEG. We want to use the blinkenlights to show source(s) and destination as the information doesn't fit on the screen.
- [ ] shift-delete for quick deletion?

2023-07-10 02:57 UTC, m-m-adams commented
What about highlighting destinations when a source shortcut is clicked, the inverse of the current click destination to highlight sources behaviour?

2023-08-08 19:47 UTC, bfredl commented
Now it is usable across devices. the screen scroll on 7seg is maybe not very readable (would need to invent yet a table of short parameter names), but you can navigate using shortcut blinks which is shown now as part of the menu.

2023-08-08 23:18 UTC, m-m-adams requested changes
Code looks good to me!

I'm not sure about the multi level modulations, the way they show up without a level looks like a bug compared to the other rows.

Maybe try like this?

src1[4] src2[4] intensity[4] dest[6],

with a space on both sides and between everything, and no scrolling. I think 6 characters is clear for all the modulatable params but I admittedly haven't looked that hard

2023-08-09 19:55 UTC, bfredl commented
> src1[4] src2[4] intensity[4] dest[6],

I tried it but 6 chars for the dest is just too cramped, I am gonna use max then and for two sources shift everything and accept that those ones might need to scroll.

Too much weirdness around strings right now. (if not crashes, menu items randomly taking the wrong value). making draft until I figure out something which works.

2023-08-12 09:57 UTC, bfredl commented
Did a bit more extensive testing, and for better and worse, the remaining crashes I see are the same as already on community firmware.

2023-08-15 09:05 UTC, bfredl commented
Seems stable now after rebasing on the change to use `std::string_view` for menu items.

2023-08-17 18:49 UTC, m-m-adams approved these changes

2023-08-17 19:10 UTC, merged