Documentation and Site update for upcoming first release
SynthstromAudible/DelugeFirmware pull request #338
Opened 2023-08-11 12:32 UTC by PaulFreund

Since we are working torwards our first release cycle this PR is to clean up documentation and update the site for clear coummunication with end users. Moves Debug and DIY hardware guide into Wiki

Scope:
 - [x] Update readmes and split into respective docs files
 - [x] Update release strategy and branch mentions

Moved out of scope:
 - Create website landing page with clear instructions and download link
 - Move nightly downloads into GitHub releases function
 - Add issue template (picked up by @seangoodvibes)
 - Maybe split community features into multiple files (feedback wanted, reason is to automatically render them on the site with date)
 - If above is done implement a renderer for the feature markdowns
 - Add switch to show developer information
 - Include Doxygen in developer mode
 - If WebMIDI hanging can be circumvented add MyDeluge function with @bfredl's SysEx tools in developer mode

2023-08-12 13:28 UTC, seangoodvibes commented
I agree with features having their own documentation page. This way you can go into more detail about your feature and provide thorough instructions on how to use it.

2023-08-13 13:26 UTC, sichtbeton commented
> Create website landing page with clear instructions and download link

Why not use the wiki? It would be the first and most logical place to look for stuff like this.

2023-08-24 07:16 UTC, trappar commented on README.md
> +* To learn about the toolchain, application and start working on the code continue with [docs/dev/getting_started.md](docs/dev/getting_started.md)
```suggestion
* To contribute to the project with code, bug reports, suggestions, and feedback see: [How to contribute to Deluge Firmware](CONTRIBUTING.md)
* To learn about the toolchain, application, and to start working on the code continue with: [Getting Started with Deluge Development](docs/dev/getting_started.md)
```

2023-08-24 07:16 UTC, trappar commented on docs/dev/getting_started.md
> +## Obtaining the Source Code
Should add a top level title above this like:
```markdown
# Getting Started with Deluge Development
```

2023-08-24 07:16 UTC, trappar commented on README.md
> +# Dear Deluge owners
Switch headings to second level and add top level title like:
```markdown
# Synthstrom Deluge Firmware
```

2023-08-24 07:16 UTC, trappar commented on docs/dev/getting_started.md
> +# Futher reading
Switch this to second level heading for consistency.

2023-08-24 15:31 UTC, seangoodvibes requested changes

2023-08-24 15:31 UTC, seangoodvibes commented on CONTRIBUTING.md
> +4. Once the Pull request is ready, fulfills all requirements outlined above and is up to date with the `community` branch it can be converted from Draft and marked as ready for review.
Add comma here after the word above:

"fulfills all requirements outlined above,"

add comma after branch "branch, it can be converted ..."

2023-08-24 15:50 UTC, seangoodvibes approved these changes
Approved!

2023-08-24 16:01 UTC, merged