Load synth presets into kit rows
SynthstromAudible/DelugeFirmware pull request #395
Opened 2023-08-21 21:14 UTC by m-m-adams

Pseudo draft - it's working but hacky, I need to do a review and figure out what can get cut back now

2023-08-21 22:02 UTC, m-m-adams commented
I think it's good now

2023-08-21 23:06 UTC, seangoodvibes commented on src/deluge/gui/ui/load/load_instrument_preset_ui.cpp
> +	ParamManager* parammanager;
can you change parammanager to paramManager :)?

2023-08-21 23:07 UTC, seangoodvibes commented on src/deluge/gui/ui/load/load_instrument_preset_ui.cpp
> +	parammanager = currentSong->getBackedUpParamManagerPreferablyWithClip(soundDrumToReplace, instrumentClipToLoadFor);
parammanager >> paramManager

2023-08-21 23:10 UTC, seangoodvibes requested changes
Just one minor formatting change and then you're good to go.

2023-08-22 02:26 UTC, seangoodvibes approved these changes
Looks good. Approved!

2023-08-22 02:45 UTC, merged

2023-08-22 06:41 UTC, soymonitus commented
This needs to be rolled back i think! Loading kits (LOAD + Kit) no longer works, it shows the synth selector. Loading a synth also doesn't work, the synth doesn't change. Also when holding a row in Song mode and changing its type makes the Deluge hang

2023-08-22 06:46 UTC, soymonitus commented
Reverted this commit to test again and confirmed everything works good without this change applied