Fixed clip button blinking
SynthstromAudible/DelugeFirmware pull request #397
Opened 2023-08-21 22:45 UTC by seangoodvibes

Fixed the clip button blinking in audio clip view as a result of the automation view implementation

This resolves issue #371

2023-08-22 02:53 UTC, m-m-adams requested changes
This has a regression - holding clips that are in automation view no longer blinks the clip light

2023-08-22 17:11 UTC, m-m-adams commented
This now only somewhat fixes the bug - the clip button will flash while holding down an audio clip but stop when you enter it

2023-08-22 22:39 UTC, seangoodvibes commented
@m-m-adams attempt #2 to fix the regression has been committed!

2023-08-24 00:43 UTC, m-m-adams approved these changes

2023-08-24 00:44 UTC, merged