Feature: Midi Follow Mode + Midi Learning View
SynthstromAudible/DelugeFirmware pull request #781
Opened 2023-12-02 21:24 UTC by seangoodvibes

# Midi Follow Mode with Midi Learning View

<img width="835" alt="Screen Shot 2023-12-02 at 4 07 59 PM" src="https://github.com/SynthstromAudible/DelugeFirmware/assets/138174805/374fcf48-1316-4b21-9d7e-87e233f4057b">

## Description:

Master midi follow mode whereby after enabling the mode, you set a master midi follow channel and all midi received on that channel will be directed to the active view (e.g. arranger view, song view, audio clip view, instrument clip view).

- Note: Your existing midi learnings on other channels will remain untouched and can be used together with the master midi follow mode

### **Turn Follow Mode On and Set Master Midi Follow Channel**

To turn follow mode on and set the master midi follow channel, enter the settings menu and go to the sub menu for Midi -> Midi-Follow

- In the Midi-Follow > Follow submenu, set this feature to Enabled or Disabled
- In the Midi-Follow > Channel submenu, set the channel between 1 and 16

### **Notes:**
For notes, the functionality is simple: notes received on the master midi channel will play the instrument in the active clip (e.g. a synth, or all kit rows).

- Note: For Kit's, the bottom Kit row is mapped to note C3 (note # 60). All kit rows above are mapped to note's incrementally (e.g. 60, 61, 62, etc.).

### **CC's:**
For CC's, you need to learn your midi CC's to the parameters you want to control. You do this by entering a Midi Learning View accessible from the Song View by pressing Learn + Midi. You also exit this view by pressing Learn + Midi.

In the Midi Learning View, the shortcut pads for all the Parameters that can be controlled on the deluge are illuminated. By default, no CC's are learned and all shortcut pads are illuminated dimly. 

In order to learn a Midi CC to a Parameter, press and hold on the shortcut pad for the parameter and send a Midi CC with your controller (e.g. turn knob, move fader up/down). The shortcut pad will now be illuminated white indicating that that parameter has been learned. The display will also indicate the midi CC that the parameter has been learned to.

A parameter can only be learned to one midi CC. Conversely, a midi CC can be learned to multiple parameters.

You can get an overview of what parameters a midi CC has been mapped to by holding the Midi button and turning Midi CC on your controller. The parameter shortcuts mapped to that midi CC will be illuminated green.

After you have finished learning your Midi CC's, simply exit Midi Learning View (with Learn + Midi) and your midi CC's will now control the parameters you have learned. The parameters are controlled only in the current context.

- So if you learn filter for example, while in song view it will only control the song’s filter. If you enter a specific synth clip, it will only control that synths filter, if you are in a kit clip it will either control the entire kit or a specific row in that clip (depending on whether you have affect entire enabled or not)
- In other words it checks what context you’re in and controls the parameters of that context.

## Re-cap of functionality

1. Added new Midi submenu for Midi-Follow where you can turn Enable or Disable Midi Follow Mode and set the Midi Follow Channel
2. Added new Midi Learning View accessible with Learn + Midi from Song View where you can learn Midi CC's to control Parameters on the deluge
3. When Midi Follow Mode is enabled, a Midi Follow Channel has been set, and you have learned your Midi CC's, your external controller's Notes and Midi CC's will be automatically directed to control the Notes of the Active Instrument (e.g. Synth, Kit, Midi, CV) or the Parameters of the Active View (e.g. Song View, Arranger View, Audio Clip View, Instrument Clip View).

2023-12-04 13:42 UTC, soymonitus commented
I found something in your branch. At the beginning I posted it thinking it was a Release 1.0 bug but then realized it works on 1.0 community release, but not on your branch.

The quantized stutter feature doesn't work as before. Now when you select for example rate 32nd (3 leds lit up) it starts stuttering but the leds are not centered. As soon as you move a little bit the golden knob, the rate changes abruptly to the one that would have 3 leds lit up. If you turn it to center it (2 leds lit) you will find again the selected initial rate (32nds).
@seangoodvibes

What is the expected behavior?
When you press the golden knob, no matter which rate you selected, the LEDs update to show just 2 leds lit up (centered position) and when you move up or down you change the rate from your selected initial rate, being the center always the initial point, and not do an abrupt change

2023-12-04 13:52 UTC, seangoodvibes commented
> I found something in your branch. At the beginning I posted it thinking it was a Release 1.0 bug but then realized it works on 1.0 community release, but not on your branch.
> 
> 
> 
> The quantized stutter feature doesn't work as before. Now when you select for example rate 32nd (3 leds lit up) it starts stuttering but the leds are not centered. As soon as you move a little bit the golden knob, the rate changes abruptly to the one that would have 3 leds lit up. If you turn it to center it (2 leds lit) you will find again the selected initial rate (32nds).
> 
> 
> 
> What is the expected behavior?
> 
> When you press the golden knob, no matter which rate you selected, the LEDs update to show just 2 leds lit up (centered position) and when you move up or down you change the rate from your selected initial rate, being the center always the initial point, and not do an abrupt change

Hey I saw you opened an issue but closed it.

As part of performance view, I adjusted the implementation of quantized stutter. It sounds the same but the LED's don't behave the same.

In the previous quantized stutter implementation, the value of stutter rate was changed to 0 prior to the calculation of the quantized stutter rate.

This why the LED'd would always reset to 0 when enabling stutter.

Instead of doing that, which causes problems for the menu not showing the right stutter rate (this wasn't visible before because we didn't have a stutter rate menu, now we do), I instead adjusted the calculation for quantized stutter to center around 0 without needing to adjust stutter rate.

It's not a bug but rather an intended change.

So now because I'm not actually touching the stutter rate and changing it to 0, the parameter value and the LED's which reflect it don't change.

2023-12-04 15:47 UTC, soymonitus commented
But then the behavior looks buggy. When you select for example 4ths (no leds lit), then press the knob, then the stutter begins. In the pressed state, now the center point (2 leds lit) would be stuttering at 4ths division, but your "pointer" is now in the extreme of the range (no leds lit), but the 4ths stuttering is sounding (like if you were in the center (2 leds lit), so the moment you move a tiny bit the knob, the stutter rate value is overriden suddenly from 4ths to... maybe whole notes, because you jumped to no LEDs lit, and to come back to what was sounding before your tiny movement, you have to turn the knob to the center. I don't know if I am explaining. There is a incongruity between the LEDs and the real value. Wouldn't it fix your issue with performance view to make some specific logic for the quantized stutter, to show the text "4ths" "8ths" etc instead of numbers, and to make use of the stutterer.lastQuantizedKnobDiff ?

P.D: I saw that what changed the behavior was moving this piece of code from beginStutter to endStutter:


	```
	// When stuttering, we center the value at 0, so the center is the reference for the stutter rate that we selected just before pressing the knob
		// and we use the lastQuantizedKnobDiff value to calculate the relative (real) value
		unpatchedParams->params[Param::Unpatched::STUTTER_RATE].setCurrentValueBasicForSetup(0);
		view.notifyParamAutomationOccurred(paramManager);
```

2023-12-05 15:37 UTC, m-m-adams requested changes
Please remove the performance view commits from this branch - it's not feasible to review this PR right now

2023-12-05 23:59 UTC, seangoodvibes commented
> i deeply appreciate this great progress to improve the usability with anything MIDI. thank you for your efforts.
> 
> just a quick question: would CC messages be recorded when they're not assigned to one of Deluge's voice parameters?

What do you mean by "recorded"? 

CC messages received that are not assigned as part of Midi Learning View or not Learned through the regular Deluge mechanism are not dealt with as they aren't found in any mapping. So no further processing is taken with the cc message received.

2023-12-11 16:34 UTC, seangoodvibes commented on src/deluge/gui/ui/sound_editor.cpp
might not need to check for root UI here.

2023-12-11 16:35 UTC, seangoodvibes commented on src/deluge/gui/ui/sound_editor.cpp
> +}
might not need to check for root UI here, I think if menuItem record 0 is midiFollowSubmenu then it means it's the soundEditor root menu

2023-12-11 16:35 UTC, seangoodvibes commented on src/deluge/gui/menu_item/performance_session_view/editing_mode.h
>  		uiNeedsRendering(&performanceSessionView);
undo this change

2023-12-11 16:50 UTC, seangoodvibes commented on src/deluge/model/instrument/melodic_instrument.cpp
>  #include "gui/views/instrument_clip_view.h"
I don't think I need this automation view include

2023-12-11 16:51 UTC, seangoodvibes commented on src/deluge/model/mod_controllable/mod_controllable_audio.h
remove this orphaned bool

2023-12-11 16:52 UTC, seangoodvibes commented on src/deluge/modulation/params/param_collection.cpp
>  	if (currentValueChanged || automationChanged) {
remove these changes

2023-12-11 16:54 UTC, seangoodvibes commented on src/deluge/gui/views/midi_session_view.cpp
> +void MidiSessionView::renderRow(uint8_t* image, uint8_t occupancyMask[], int32_t yDisplay) {
explain that this is drawing the shortcut pads on the grid and their learned status

2023-12-11 16:54 UTC, seangoodvibes commented on src/deluge/gui/views/midi_session_view.cpp
> +bool MidiSessionView::renderSidebar(uint32_t whichRows, uint8_t image[][kDisplayWidth + kSideBarWidth][3],
remove (yet)

2023-12-11 16:55 UTC, seangoodvibes commented on src/deluge/gui/views/midi_session_view.cpp
> +
Add Render Synth, Kit, Param comment

2023-12-11 16:57 UTC, seangoodvibes commented on src/deluge/gui/views/midi_session_view.cpp
> +}
do I use the previousCCValueSent struct? I don't think so. Remove.

2023-12-11 16:58 UTC, seangoodvibes commented on src/deluge/gui/views/midi_session_view.cpp
> +	else if (b == MIDI) {
not just exiting, add description that it will highlight learned params also when learn is held

2023-12-11 16:59 UTC, seangoodvibes commented on src/deluge/gui/views/midi_session_view.cpp
> +		//let go of pad
let go of pad, reset view display and pad press history

2023-12-11 17:01 UTC, seangoodvibes commented on src/deluge/gui/views/midi_session_view.cpp
> +void MidiSessionView::cantLearn(int32_t channel) {
add documentation - error message displayed when you try to learn a midi cc to a param on a channel different from the midi follow param channel

2023-12-11 17:01 UTC, seangoodvibes commented on src/deluge/gui/views/midi_session_view.cpp
> +void MidiSessionView::modEncoderButtonAction(uint8_t whichModEncoder, bool on) {
remove this stutter comment

2023-12-11 17:02 UTC, seangoodvibes commented on src/deluge/gui/views/midi_session_view.cpp
> +
add description of what this code is doing - it's seeing if it can get a clip from the current context

2023-12-11 17:04 UTC, seangoodvibes commented on src/deluge/gui/views/midi_session_view.cpp
> +
maybe refactor this function into multiple sub functions

2023-12-11 17:05 UTC, seangoodvibes commented on src/deluge/gui/views/midi_session_view.cpp
> +void MidiSessionView::updateMappingChangeStatus() {
add description

it's looking to see if there are any changes to the midi cc mappings since the last time you loaded saved settings

2023-12-11 17:07 UTC, seangoodvibes commented on src/deluge/model/drum/kit.cpp
> +	Clip* clip = nullptr;
call function in midi session view to get clip for active context

2023-12-11 17:21 UTC, seangoodvibes commented on src/deluge/model/mod_controllable/mod_controllable_audio.cpp
> +					//	if (midiEngine.midiFollowDisplayParam) {
To do add a default to the menu hide/display mod encoder popups

2023-12-11 17:23 UTC, seangoodvibes commented on src/deluge/model/mod_controllable/mod_controllable_audio.cpp
> +
Add description of what this function is doing

2023-12-11 17:23 UTC, seangoodvibes commented on src/deluge/model/mod_controllable/mod_controllable_audio.cpp
> +int32_t ModControllableAudio::calculateKnobPosForMidiTakeover(ModelStackWithAutoParam* modelStackWithParam,
explain what this function is doing

2023-12-18 23:44 UTC, Queroland commented
Hey, sorry - I don`t know where else to write.. youre doing amazing work! This feature will be sensational and will change the way we can use the deluge drastically.. I also wanted to do it, described my intention here, but died over it - have no modified deluge for programming, no big glue of C++ (C# professional), it`s just not possible without propper programming interface. I went crazy when I saw your opened request and how detailed you planned this function with learn view and feedback and root note for kits! I wish you good luck, a lot of fun pushing this into the dely, no gray hairs and a happy holidays ! :) Cheers, Roland form germany

2023-12-18 23:53 UTC, seangoodvibes commented
> Hey, sorry - I don`t know where else to write.. youre doing amazing work! This feature will be sensational and will change the way we can use the deluge drastically.. I also wanted to do it, described my intention here, but died over it - have no modified deluge for programming, no big glue of C++ (C# professional), its just not possible without propper programming interface. I went crazy when I saw your opened request and how detailed you planned this function with learn view and feedback and root note for kits! I wish you good luck, a lot of fun pushing this into the dely, no gray hairs and a happy holidays ! :) Cheers, Roland form germany

Aww thank you for the kind words! It's definitely been a fun adventure building this feature and I'm really excited for when it will be finished (hopefully soon!) and everyone can enjoy it. It's going to be a huge quality of life upgrade for the Deluge and I can't wait to relax and just play with it :D! 

Happy Holidays and thank you for looking out for my grey hairs hahah! <3

2023-12-27 01:57 UTC, closed without merging