dbt: only do python setup if the toolchain is freshly unpacked
SynthstromAudible/DelugeFirmware pull request #981
Opened 2024-01-15 04:25 UTC by bobtwinkles

This has significant performance benefits to DBT startup time (>1 second to <45ms) which is especially helpful when using DBT as a proxy for `clang-format` in an editor's autoformat configuration.

2024-01-15 06:06 UTC, bobtwinkles commented
This needs to be tested by users on Windows, Linux, and OSX before merging

2024-01-15 06:48 UTC, m-m-adams commented
Works on mac, time is the same with and without DBT_NO_PYTHON_UPGRADE=1

2024-01-15 15:21 UTC, cowboy requested changes
Works great here in Linux. It's significantly faster!

In native Windows, however, there are some issue. See my other comments.

2024-01-15 15:21 UTC, cowboy commented on scripts/toolchain/dbtenv.cmd
> +    set /p "DBT_TOOLCHAIN_INSTALLED=1"
Apparenrtly, `set /p` waits for user input - which makes sense when reading from a file as in `set /p VARNAME=<"%FILENAME%"` but not here!

2024-01-15 15:21 UTC, cowboy commented on scripts/toolchain/dbtenv.cmd
> +        %PIP_CMD% install -q --upgrade pip | find /V "already satisfied"
I'm seeing some errors, and I don't know enough to troubleshoot them. Sometimes, the script leaves a `win32-x86_64-10.zip` file and `win32-x86_64` directory in the project root, but I'm not sure how to repro that.

PowerShell:

```
PS C:\Users\Cowboy\projects\DelugeFirmware> .\dbt
Downloading Windows toolchain..done!
Extracting Windows toolchain..moving..done!
Cleaning up temporary files..done!
DBT: Toolchain freshly installed, running python setup
'install' is not recognized as an internal or external command,
operable program or batch file.
```

Git Bash:

```
$ ./dbt.cmd
Downloading Windows toolchain..done!
Extracting Windows toolchain..moving..done!
Cleaning up temporary files..done!
DBT: Toolchain freshly installed, running python setup
install: unknown option -- q
Try 'install --help' for more information.
find: '/V': No such file or directory
find: 'already satisfied': No such file or directory
install: unknown option -- q
Try 'install --help' for more information.
find: '/V': No such file or directory
find: 'already satisfied': No such file or directory
usage: dbt [-h] [<subcommand>]

positional arguments:
  <subcommand>

options:
  -h, --help    print this help message

subcommands:
  Building:
    build [-h] [-S] [-v] [-c] [-t TYPE] [-m] [{release,debug,relwithdebinfo,all}]
      Build the Deluge firmware
    clean [-h]
      Cleanup any build artifacts in the current environment
    configure [-h] [-f] [-m] [-t {dev,nightly,alpha,beta,rc,release}]
      Configure a CMake build (automatically called by build)
    nuke [-h]
      Indiscriminately removes any build tree contents and artifacts
    scons [-h]
      Run SCons in the current environment (deprecated)
  Debugging:
    debug [-h] [-j] [-c COMMAND] [-d TARGET_DEVICE] [-g GDB_PORT] [-v] [-p {swd,jtag}] [-i INTERFACE]
      Run a debug server (JLink or OpenOCD)
    gdb [-h] [-nb] [{7seg,oled}]
      Open a GDB remote for the proper target
    openocd [-h] [-v]
      Run OpenOCD with default arguments (CMSIS-DAP/DelugeProbe).
      These can be changed using the OPENOCD_OPTS variable.
  Development:
    docs [-h] [-R]
      Open the docs for the Deluge Firmware (rebuilding if necessary)
    shell [-h]
      Open a shell in the DBT environment
  Miscellaneous:
    format [-h] [-nr] [-q] [-v] [-c] [directory]
      Formats files using clang-format (Assumes .clang-format present in directory structure)
    license [-h] [-r] [-q] [-d] [-v] directory
      Add Synthstrom Deluge license prelude to files (if not present)
  Ungrouped:
    test [-h]
      Run deluge tests
```

2024-01-15 15:21 UTC, cowboy commented on scripts/toolchain/dbtenv.cmd
> +set /p "DBT_TOOLCHAIN_INSTALLED=0"
Apparenrtly, `set /p` waits for user input - which makes sense when reading from a file as in `set /p VARNAME=<"%FILENAME%"` but not here!

2024-01-15 15:22 UTC, cowboy commented on scripts/toolchain/dbtenv.cmd
> +    set /p "DBT_TOOLCHAIN_INSTALLED=1"
Apparenrtly, `set /p` waits for user input - which makes sense when reading from a file as in `set /p VARNAME=<"%FILENAME%"` but not here!

2024-01-15 15:22 UTC, cowboy commented on scripts/toolchain/dbtenv.cmd
> +    set /p "DBT_TOOLCHAIN_INSTALLED=1"
Apparenrtly, `set /p` waits for user input - which makes sense when reading from a file as in `set /p VARNAME=<"%FILENAME%"` but not here!

2024-01-15 16:04 UTC, m-m-adams commented
Works on fedora linux too, so other than windows this should be good to go

2024-01-16 02:49 UTC, cowboy approved these changes
Works great now in PowerShell! I say :shipit:

2024-01-16 03:22 UTC, bobtwinkles commented
Cool, thanks everyone for testing. I think this is probably ready to merge?

2024-01-16 18:20 UTC, stellar-aria commented
Works in cmd, LGTM
:shipit:

2024-01-16 18:20 UTC, stellar-aria approved these changes

2024-01-16 18:24 UTC, merged